options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
  - args: ['build', '-t', 'gcr.io/$PROJECT_ID/pdf-processor:$COMMIT_SHA', '.']
  options:
     machineType: 'E2_HIGHCPU_8'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pdf-processor:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pdf-processor'
      - '--image=gcr.io/$PROJECT_ID/pdf-processor:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--allow-unauthenticated'
      - '--timeout=300s'

images:
  - 'gcr.io/$PROJECT_ID/pdf-processor:$COMMIT_SHA'
